name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

      # 🔥 Inject google-services.json (for Debug variant)
    - name: Decode google-services.json for Debug
      run: |
       mkdir -p app/src/debug
       echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > app/src/debug/google-services.json

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    # ✅ Run Android Lint
    - name: Run Android Lint
      run: ./gradlew lintDebug
          
    # ✅ Upload Lint Report
    - name: Upload Lint Report
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: app/build/reports/lint-results-debug.html

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
